adminpanel/urls.py
from django.urls import path
from . import views

app_name = "adminpanel"

urlpatterns = [
     path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
     path("create-client/", views.CreateClientView.as_view(), name="create_client"),
     path("create-task/", views.CreateTaskView.as_view(), name="create_task"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index")
]

taskhub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace = "accounts"), ),
    path("", include(("core.urls", "core"), namespace = "core"), ),
    path("client/", include(('clients.urls', 'client'), namespace='client'), ),
    path("adminpanel/", include(("adminpanel.urls", "adminpanel"), namespace = "adminpanel"), )
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

adminpanel/models.py
from django.db import models

# Create your models here.

adminpanel/forms.py
from django import forms
from accounts.models import CustomUser
from core.models import Task
from core.mixins import BootstrapFormMixin

class CreateClientForm(BootstrapFormMixin, forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["email", "name"]

class CreateTaskForm(BootstrapFormMixin, forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description", "client", "deadline", "file", ]        

adminpanel/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from core.mixins import AdminRequiredMixin
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from accounts.models import CustomUser
from core.models import Task
from .forms import CreateClientForm, CreateTaskForm
from core.utils import temp_password_generator, send_notification, success_message

# Create your views here.

class DashboardView(LoginRequiredMixin, AdminRequiredMixin, ListView):
    model = CustomUser
    template_name = "adminpanel/dashboard.html"
    context_object_name = "clients"

    def get_queryset(self):
        return CustomUser.objects.filter(role = "client").prefetch_related("tasks")
    
    def get(self, request, *args, **kwargs):
        success_message(request, "Page loaded successfully!")
        return super().get(request, *args, **kwargs)


class CreateClientView(LoginRequiredMixin, AdminRequiredMixin, CreateView):
    model = CustomUser
    form_class = CreateClientForm
    template_name = 'adminpanel/create_client.html'
    success_url = reverse_lazy("adminpanel:dashboard")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.role = 'client'
        user.first_login = True

        random_password = temp_password_generator()
        user.set_password(random_password)
        user.save()

        form_email = form.cleaned_data["email"]
        form_name = form.cleaned_data["name"]

        send_notification (
            subject = "New TaskHub account",
            message = f"Hello {form_name}, an account has been created for you. \n\n Your email is: {form_email} \n Your password is {random_password}. \n\n You will be prompted to change your password on your first login.",
            to_email = [form_email],
        )

        success_message(
            self.request,
            f"Client {form_name} created Successfully! \n"
            f"Email: {form_email} | Password: {random_password} \n"
            "An email has been sent to the client providing their login details."
        )

        return super().form_valid(form)
    

class CreateTaskView(LoginRequiredMixin, AdminRequiredMixin, CreateView):
    model = Task
    form_class = CreateTaskForm
    template_name = 'adminpanel/create_task.html'
    success_url = reverse_lazy("adminpanel:dashboard")

    def form_valid(self, form):
        form.save()

        form_client = form.cleaned_data["client"]
        client_email = form_client.email
        client_name = form_client.name

        send_notification(
            subject = "New Task",
            message = f"Hello {client_name}, \n\n There has been a new task asigned to you on your TaskHub account.",
            to_email = [client_email],
        )

        form_task = form.cleaned_data["title"]

        success_message(
            self.request,
            f"The Task: {form_task} has been successfully created and asigned to {client_name} \n"
            "They have been notified of this."
        )

        return super().form_valid(form)

    

adminpanel/templates/adminpanel/admin_base.html
{% extends "base.html" %}

{% block title %} adminpanel | {{ block.super }} {% endblock %}

{% block header %} {% endblock %}

{% block footer %} {% endblock %}

adminpanel/templates/adminpanel/create_client.html
{% extends "adminpanel/admin_base.html" %}

{% block title %} Create Client | {{block.super}} {% endblock %}

{% block content %} 
<h1>Create a new Client</h1>

<form method="post">
    {% csrf_token %}

    {% include "core/includes/form.html" %}

    <button type="submit">Create Client</button>
</form>

{% endblock %}

adminpanel/templates/adminpanel/create_task.html
{% extends "adminpanel/admin_base.html" %}

{% block title %} Create Task | {{block.super}} {% endblock %}

{% block content %} 
<h1>Create a new Task</h1>

<form method="post">
    {% csrf_token %}

    {% include "core/includes/form.html" %}

    <button type="submit">Create Task</button>
</form>

{% endblock %}

adminpanel/templates/adminpanel/dashboard.html
{% extends "adminpanel/admin_base.html" %}

{% block title %} Dashboard | {{block.super}} {% endblock %}

{% block css_files %} {% endblock %}


{% block content %}

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}

    <form method="post" action="{% url 'adminpanel:create_client' %}">
    {% csrf_token %}

    <button type="submit">Create a new Client</button>
</form>

<form method="post" action="{% url 'adminpanel:create_task' %}">
    {% csrf_token %}

    <button type="submit">Create a new Task</button>
</form>    

    <h1>Admin Panel</h1>

    <div>
        {% for client in clients %}
            <div>

                <h2>{{ client.name}}</h2>

                <div>
                    <h3>Tasks</h3>

                    {% for task in client.tasks.all %}

                        <div>
                            <p>{{ task.title }}</p>
                        </div>

                    {% empty %}

                        <p>This client currently has no Tasks asigned.</p>

                    {% endfor %}

                </div>

            </div>
        {% endfor %}
    </div>

{% endblock %}